# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


apiVersion: 1

datasources:
  - name: 'feldera'
    type: 'feldera-feldera-datasource'
    access: proxy
    isDefault: false
    orgId: 1
    version: 1
    editable: true
    jsonData:
      baseUrl: 'http://feldera:8080'
      pipeline: 'otel'
    secureJsonData:
      apiKey: ''
